import React from "react";
import { Icon } from "@iconify/react";

export const MenuIngredient = [
  {
    name: "เนื้อสัตว์",
    icon: <Icon icon="noto:cut-of-meat" />,
    keyword: "Meat",
  },
  {
    name: "อาหารทะเล",
    icon: <Icon icon="noto:crab" />,
    keyword: "Sea",
  },
  {
    name: "พืชผัก",
    icon: <Icon icon="noto:broccoli" />,
    keyword: "Vet",
  },
  {
    name: "ผลไม้",
    icon: <Icon icon="noto:grapes" />,
    keyword: "Fruit",
  },
  {
    name: "ไข่ นม เนย ชีส",
    icon: <Icon icon="noto:cheese-wedge" />,
    keyword: "Egg",
  },
  {
    name: "ผลิตภัณฑ์แปรรูปแช่เย็น",
    icon: <Icon icon="noto:ice" />,
    keyword: "Frozen",
  },
  {
    name: "ผลัตภัณฑ์เนื้อสัตว์แปรรูป",
    icon: <Icon icon="emojione:bacon" />,
    keyword: "Transform",
  },
  {
    name: "อาหารแห้ง",
    icon: <Icon icon="noto:rice-ball" />,
    keyword: "Dry",
  },
];

export const materialMeat = [
  { id: 1, name: "Egg", src: "/images/ingredients/หมู.png" },
  { id: 2, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 3, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 4, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 5, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 6, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 7, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 8, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 9, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 10, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 11, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 12, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 13, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 14, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 15, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 16, name: "P", src: "/images/ingredients/หมู.png" },
];

export const materialSea = [
  { id: 17, name: "Sea", src: "/images/ingredients/หมู.png" },
  { id: 18, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 19, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 20, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 21, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 22, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 23, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 24, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 25, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 26, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 27, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 28, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 29, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 30, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 31, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 32, name: "P", src: "/images/ingredients/หมู.png" },
  { id: 129, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 130, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 131, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 132, name: "P", src: "/images/ingredients/หมู.png" },
  { id: 133, name: "P", src: "/images/ingredients/หมู.png" },
];

export const materialVegetable = [
  { id: 33, name: "Vegetable", src: "/images/ingredients/หมู.png" },
  { id: 34, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 35, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 36, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 37, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 38, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 39, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 40, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 41, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 42, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 43, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 44, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 45, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 46, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 47, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 48, name: "P", src: "/images/ingredients/หมู.png" },
];

export const materialFruit = [
  { id: 49, name: "Fruit", src: "/images/ingredients/หมู.png" },
  { id: 50, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 51, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 52, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 53, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 54, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 55, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 56, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 57, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 58, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 59, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 60, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 61, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 62, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 63, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 64, name: "P", src: "/images/ingredients/หมู.png" },
];

export const materialEggMilkButterCheese = [
  { id: 65, name: "EggMilkButterCheese", src: "/images/ingredients/หมู.png" },
  { id: 66, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 67, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 68, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 69, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 70, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 71, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 72, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 73, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 74, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 75, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 76, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 77, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 78, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 79, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 80, name: "P", src: "/images/ingredients/หมู.png" },
];

export const materialFrozen = [
  { id: 81, name: "Frozen", src: "/images/ingredients/หมู.png" },
  { id: 82, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 83, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 84, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 85, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 86, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 87, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 88, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 89, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 90, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 91, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 92, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 93, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 94, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 95, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 96, name: "P", src: "/images/ingredients/หมู.png" },
];

export const materialMeatTransform = [
  { id: 97, name: "Transform", src: "/images/ingredients/หมู.png" },
  { id: 98, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 99, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 100, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 101, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 102, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 103, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 104, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 105, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 106, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 107, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 108, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 109, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 110, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 111, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 112, name: "P", src: "/images/ingredients/หมู.png" },
];

export const materialDry = [
  { id: 113, name: "Dry", src: "/images/ingredients/หมู.png" },
  { id: 114, name: "A", src: "/images/ingredients/หมู.png" },
  { id: 115, name: "B", src: "/images/ingredients/หมู.png" },
  { id: 116, name: "C", src: "/images/ingredients/หมู.png" },
  { id: 117, name: "D", src: "/images/ingredients/หมู.png" },
  { id: 118, name: "E", src: "/images/ingredients/หมู.png" },
  { id: 119, name: "F", src: "/images/ingredients/หมู.png" },
  { id: 120, name: "G", src: "/images/ingredients/หมู.png" },
  { id: 121, name: "H", src: "/images/ingredients/หมู.png" },
  { id: 122, name: "I", src: "/images/ingredients/หมู.png" },
  { id: 123, name: "K", src: "/images/ingredients/หมู.png" },
  { id: 124, name: "J", src: "/images/ingredients/หมู.png" },
  { id: 125, name: "M", src: "/images/ingredients/หมู.png" },
  { id: 126, name: "N", src: "/images/ingredients/หมู.png" },
  { id: 127, name: "O", src: "/images/ingredients/หมู.png" },
  { id: 128, name: "P", src: "/images/ingredients/หมู.png" },
];
